learn about numpy using vscode


### importing numpy in python

In [2]:
import numpy as np

###  Creating array from list

In [2]:
arr_1d=np.array([1,2,3,4,5])
print("1D array: ",arr_1d)

1D array:  [1 2 3 4 5]


In [7]:
arr_2d=np.array([[1,2,3235],[2235,3,4]])
print("2D Array :",arr_2d)

2D Array : [[   1    2 3235]
 [2235    3    4]]


### List vs Numpy array


numpy arrays are faster than list


## creating array from scratch

In [9]:
zeros=np.zeros((3,4))
print("Zeros array: \n",zeros)

ones=np.ones((2,3))
print("Ones Array: \n",ones)

full=np.full((2,3),7)
print( "Full Array: \n",full)

random=np.random.random((2,3))
print("Random Array: \n",random)

sequence=np.arange(0,10,2)
print("Sequence Array \n:",sequence)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array: 
 [[7 7 7]
 [7 7 7]]
Random Array: 
 [[0.50147033 0.9398112  0.48660509]
 [0.93828141 0.48991613 0.0025921 ]]
Sequence Array 
: [0 2 4 6 8]


### Vector, Matrix and Tensor

In [13]:
vector=np.array([1,2,3,4])
print ("Vector \n",vector)

matrix=np.array([[1,2,3],[4,5,6]])
print ("Matrix \n",matrix)

tensor=np.array([[1,2],[3,4],[5,6],[6,7]])
print ("Tensor \n",tensor)



Vector 
 [1 2 3 4]
Matrix 
 [[1 2 3]
 [4 5 6]]
Tensor 
 [[1 2]
 [3 4]
 [5 6]
 [6 7]]


## Array Properties

In [ ]:
arr=np.array([[1,2,3235],
              [2235,3,4]])

print("Shape",arr.shape)
print("Dimension",arr.ndim)
print("Size",arr.size)
print("DType",arr.dtype)



Shape (2, 3)
Dimension 2
Size 6
DType int64


### Array Reshaping

In [22]:
arr1=np.arange(12)
print("Original Array:\n",arr1)

reshaped=arr1.reshape((4,3))
print("Reshaped Array: \n",reshaped)

flattened=reshaped.flatten()
print("Flattened Array: \n",flattened)

#ravel returns original instead of the copy 

raveled=reshaped.ravel()
print("Raveled Array :\n",raveled)

#Transpose
Transpose=reshaped.T
print("Transpose: \n",Transpose)

Original Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Flattened Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose: 
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
